set_property SRC_FILE_INFO {cfile:D:/vivadoproject/Tero/Tero.srcs/constrs_1/new/place.xdc rfile:../../../Tero.srcs/constrs_1/new/place.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells tero_inst/N1/LUT6_inst]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y47 [get_cells tero_inst/N1/LUT6_inst]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells tero_inst/N2/LUT6_inst]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y46 [get_cells tero_inst/N2/LUT6_inst]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells tero_inst/N1/LUT6_inst]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells tero_inst/N2/LUT6_inst]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells {tero_inst/stage1[0].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells {tero_inst/stage1[1].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells {tero_inst/stage1[2].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells {tero_inst/stage1[3].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells {tero_inst/stage1[4].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells {tero_inst/stage1[5].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells {tero_inst/stage1[6].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells {tero_inst/stage2[0].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells {tero_inst/stage2[1].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells {tero_inst/stage2[2].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells {tero_inst/stage2[3].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells {tero_inst/stage2[4].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells {tero_inst/stage2[5].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells {tero_inst/stage2[6].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {tero_inst/stage1[0].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y47 [get_cells {tero_inst/stage1[0].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {tero_inst/stage1[1].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y47 [get_cells {tero_inst/stage1[1].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {tero_inst/stage1[2].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y47 [get_cells {tero_inst/stage1[2].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {tero_inst/stage1[3].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y47 [get_cells {tero_inst/stage1[3].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {tero_inst/stage1[4].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X6Y47 [get_cells {tero_inst/stage1[4].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {tero_inst/stage1[5].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X6Y47 [get_cells {tero_inst/stage1[5].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {tero_inst/stage1[6].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X6Y47 [get_cells {tero_inst/stage1[6].S1/LUT6_inst}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {tero_inst/stage2[0].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y46 [get_cells {tero_inst/stage2[0].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {tero_inst/stage2[1].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y46 [get_cells {tero_inst/stage2[1].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {tero_inst/stage2[2].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y46 [get_cells {tero_inst/stage2[2].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {tero_inst/stage2[3].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y46 [get_cells {tero_inst/stage2[3].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {tero_inst/stage2[4].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X6Y46 [get_cells {tero_inst/stage2[4].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {tero_inst/stage2[5].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X6Y46 [get_cells {tero_inst/stage2[5].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {tero_inst/stage2[6].S2/LUT6_inst}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X6Y46 [get_cells {tero_inst/stage2[6].S2/LUT6_inst}]
